### ISSUE TITLE
I have merged media3 exoplayer, you can last code here

### ISSUE THREAD

**Issue by liuchuancong** [jhomlala/betterplayer#1269]
```
  better_player:
    git: 
      url: https://github.com/liuchuancong/better_player.git
      ref: 'media3'
```
