### ISSUE TITLE
[FEATURE] Please update to support latest Flutter 3.22.0

### ISSUE THREAD

**Issue by bimemto** [jhomlala/betterplayer#1302]
I face this error when build with Flutter 3.22.0:

better_player-0.0.83/lib/src/configuration/better_player_controls_configuration.dart:243:34: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../../fvm/versions/3.22.0/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
      textColor: theme.textTheme.bodyText1?.color ?? Colors.white,
                                 ^^^^^^^^^

Please do a litter quick fix. Thanks and regards

**Comment by Galzysoft** [comment]
i have the same error pls update and fix the them error i think it is a minor error to fix the error is not supporting the latest flutter

**Comment by AhmedNihmet** [comment]
Any fix for this?

**Comment by Galzysoft** [comment]
> Any fix for this?

I think its just about their theming  well you can downgrade flutter to be able to use it and we keep waiting until they fix it

**Comment by waleed-brandverse** [comment]
In the mean time you can use following package import in your pubspec.yaml:
```
  better_player:
    git:
      url: https://github.com/Syed-Waleed-Shah/betterplayer.git
      ref: flutter-3.22.0-support
```

**Comment by Syed-Waleed-Shah** [comment]
In the mean time you can use following package import in your pubspec.yaml:
```
  better_player:
    git:
      url: https://github.com/Syed-Waleed-Shah/betterplayer.git
      ref: flutter-3.22.0-support
```
