### ISSUE TITLE
[BUG] A VideoPlayerController was used after being disposed when using onGenerateRoute in MaterialApp

### ISSUE THREAD

**Issue by dvirgiln** [jhomlala/betterplayer#648]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.

**Describe the bug**
There is a problem clicking the Full Screen button. Then it appears an error 
"A VideoPlayerController was used after being disposed"

The problem only happen when it is being used `onGenerateRoute`. If that line is commented, and it is uncommented the line with home, then it works fine. 

**Exception stack trace**
```
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for VideoPlayerController:
setState() or markNeedsBuild() called when widget tree was locked.

This BetterPlayerSubtitlesDrawer widget cannot be marked as needing to build because the framework is locked.
The widget on which setState() or markNeedsBuild() was called was: BetterPlayerSubtitlesDrawer
  state: _BetterPlayerSubtitlesDrawerState#a8263
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4143:9)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4153:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1287:15)
#3      _BetterPlayerSubtitlesDrawerState._updateState (package:better_player/src/subtitles/better_player_subtitles_drawer.dart:95:7)
#4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:243:25)
...
The VideoPlayerController sending notification was: VideoPlayerController#67314(VideoPlayerValue(duration: 0:10:53.803000, size: Size(1280.0, 720.0), position: 0:00:02.319000, absolutePosition: null, buffered: [DurationRange(start: 0:00:00.000000, end: 0:08:55.374000)], isPlaying: false, isLooping: false, isBuffering: false, volume: 1.0, errorDescription: null))
====================================================================================================
E/flutter (13197): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Bad state: Cannot add new events after calling close
E/flutter (13197): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
E/flutter (13197): #1      BetterPlayerController._postControllerEvent (package:better_player/src/core/better_player_controller.dart:1227:38)
E/flutter (13197): #2      BetterPlayerController.exitFullScreen (package:better_player/src/core/better_player_controller.dart:593:5)
E/flutter (13197): #3      _BetterPlayerState._pushFullScreenWidget (package:better_player/src/core/better_player.dart:260:23)
E/flutter (13197): <asynchronous suspension>
E/flutter (13197): #4      _BetterPlayerState.onFullScreenChanged (package:better_player/src/core/better_player.dart:160:7)
E/flutter (13197): <asynchronous suspension>
E/flutter (13197): 
I/ExoPlayerImpl(13197): Release d3d0d6 [ExoPlayerLib/2.14.1] [generic_x86, Android SDK built for x86, Google, 29] [goog.exo.core]
D/SurfaceUtils(13197): disconnecting from surface 0xbe9a1808, reason disconnectFromSurface

======== Exception caught by foundation library ====================================================
setState() or markNeedsBuild() called when widget tree was locked.
====================================================================================================
I/ExoPlayerImpl(13197): Init c8c660c [ExoPlayerLib/2.14.1] [generic_x86, Android SDK built for x86, Google, 29]
I/com.example.bu(13197): Background young concurrent copying GC freed 9868(913KB) AllocSpace objects, 61(4148KB) LOS objects, 3% free, 147MB/152MB, paused 9.205ms total 59.831ms

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Container(constraints: BoxConstraints(biggest)):
A VideoPlayerController was used after being disposed.

Once you have called dispose() on a VideoPlayerController, it can no longer be used.
The relevant error-causing widget was: 
  MaterialApp file:///Users/davidvirgil@hollandandbarrett.com/dev/workspace/fitwin/bug/lib/main2.dart:17:12
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:195:12)
#3      _VideoPlayerState.didUpdateWidget (package:better_player/src/video_player/video_player.dart:685:27)
#4      StatefulElement.update (package:flutter/src/widgets/framework.dart:4682:57)
...
```
**To Reproduce**
1. Copy code, 
2. Deploy code. 
3. Click in play and then click the full screen button.

**Example code*

```

import 'package:flutter/material.dart';
import 'dart:io';

import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp2());
}

class MyApp2 extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      //home: StatefulVideo("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",),
      onGenerateRoute: RouteGenerator.generateRoute,
    );
  }
}



class StatefulVideo extends StatefulWidget {
  String url;
  StatefulVideo(this.url);
  @override
  _StatefulVideoState createState() => _StatefulVideoState();
}

class _StatefulVideoState extends State<StatefulVideo>
    with TickerProviderStateMixin, AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return VideoWidget(url: widget.url,);
  }
}

class VideoWidget extends StatefulWidget {
  File file;
  String url;

  VideoWidget({this.file, this.url});

  @override
  _VideoWidgetState createState() => _VideoWidgetState(file, url);
}

class _VideoWidgetState extends State<VideoWidget> {
  File _file;
  String _url;

  _VideoWidgetState(this._file, this._url) {}

  BetterPlayerController _betterPlayerController;

  @override
  void initState() {
    super.initState();

    BetterPlayerConfiguration conf = BetterPlayerConfiguration(
        deviceOrientationsAfterFullScreen: [DeviceOrientation.portraitUp],
        controlsConfiguration: BetterPlayerControlsConfiguration(
            enableSubtitles: false,
            enableOverflowMenu: false,
            enableQualities: false,
            enableSkips: false,
            enablePlaybackSpeed: false,
            enableFullscreen: true,
            enableProgressText: false));
    BetterPlayerDataSource source;
    if (this._file != null) {
      source = BetterPlayerDataSource.file(_file.path);
    } else {
      source = BetterPlayerDataSource.network(this._url);
    }
    _betterPlayerController = BetterPlayerController(conf, betterPlayerDataSource: source);
  }

  @override
  void dispose() {
    _betterPlayerController.dispose();
    _betterPlayerController = null;
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Theme(
      // Create a unique theme with "ThemeData"
        data: ThemeData.light().copyWith(platform: TargetPlatform.android ?? Theme.of(context).platform),
        child: BetterPlayer(
          controller: _betterPlayerController,
        ));
  }
}


class RouteGenerator {
  //Client routes
  static const String SPLASH_PAGE = "/";
  static const String SPLASH_INFO_PAGE = "/splash-info";


  //Prototype routes
  //<here>


  static Route<dynamic> generateRoute(RouteSettings settings) {
    print("Routing to ${settings.name}");
    switch (settings.name){
    //Client routes
    //Common routes
      case SPLASH_PAGE:
        return MaterialPageRoute(
            maintainState: false,
            builder: (_) => StatefulVideo("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",), settings: settings);

    }
  }
}
```

pubspec.yml:

```
name: bug
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  better_player: ^0.0.72
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
```

**Flutter doctor**
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E266 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS
    ! Xcode 11.4.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Better Player version**
- Version:

**Smartphone (please complete the following information):**

**Additional context**
The problem only happens when in the MaterialApp it is being defined the onGenerateRoute
